yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('profile/', views.profile, name='profile'),
    path('posts/<int:post_id>/edit/', views.post_edit, name="post_edit"),
]

yatube/users/urls.py
from django.contrib.auth.views import (
    LoginView, LogoutView,
    PasswordResetView, PasswordResetDoneView,
    PasswordChangeView, PasswordChangeDoneView,
    PasswordResetConfirmView, PasswordResetCompleteView
)

from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'password_reset_form/',
        PasswordResetView.as_view(
            template_name='users/password_reset_form.html'
        ),
        name='password_reset_form'
    ),
    path(
        "password_reset/done/",
        PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "password_change/",
        PasswordChangeView.as_view(
            template_name="users/password_change_form.html"
        ),
        name="password_change_form",
    ),
    path(
        "password_change/done/",
        PasswordChangeDoneView.as_view(
            template_name="users/password_change_done.html"
        ),
        name="password_change_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('posts.urls', namespace='posts')),
    path("auth/", include("users.urls", namespace="users")),
    path("auth/", include("django.contrib.auth.urls")),
    path("about/", include('about.urls', namespace='about')),
]

yatube/core/models.py
from django.db import models


class CreatedModel(models.Model):
    """Абстрактная модель. Добавляет дату создания."""
    created = models.DateTimeField(
        'Дата создания',
        auto_now_add=True
    )

    class Meta:
        # Это абстрактная модель:
        abstract = True 

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.conf import settings
from django.db import models


User = get_user_model()


class Group(models.Model):

    title = models.CharField('Название группы', max_length=200)
    slug = models.SlugField('Название URL', unique=True)
    description = models.TextField('Описание группы')

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'

    def __str__(self) -> str:
        return self.title


class Post(models.Model):

    text = models.TextField('Текст поста', help_text='Введите текст')
    pub_date = models.DateTimeField('Дата', auto_now_add=True)
    group = models.ForeignKey(
        Group,
        verbose_name='Группа поста',
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        help_text='Группа, к которой будет относиться пост'
    )

    author = models.ForeignKey(
        User,
        verbose_name='Автор поста',
        on_delete=models.CASCADE,
        related_name='posts',
    )

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self) -> str:
        return self.text[:settings.SLICE_END]

yatube/posts/forms.py
from django import forms

from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group')
        labels = {
            'text': 'Текст',
            'group': 'Группа',
        }
        help_texts = {
            'text': 'Текст',
            'group': 'Группа, к которой будет относиться пост'
        }

yatube/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta():
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

yatube/about/views.py
from django.views.generic.base import TemplateView


class AboutAuthorView(TemplateView):
    template_name = 'about/author.html'


class AboutTechView(TemplateView):
    template_name = 'about/tech.html'

yatube/core/views.py
from django.shortcuts import render


def page_not_found(request, exception):
    return render(request, 'core/404.html', {'path': request.path}, status=404)

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render

from .forms import PostForm
from .models import Group, Post, User
from .utils import paginate_func


def index(request):
    post_list = Post.objects.select_related('group', 'author')
    page_obj = paginate_func(request, post_list)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.select_related('author')
    page_obj = paginate_func(request, posts)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts = author.posts.select_related('group')
    page_obj = paginate_func(request, posts)
    context = {
        'author': author,
        'page_obj': page_obj,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    context = {
        'post': post,
    }
    return render(request, 'posts/post_detail.html', context, post_id)


@login_required
def post_create(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('posts:profile', request.user.username)
    form = PostForm()

    context = {
        'form': form,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def post_edit(request, post_id):
    edit_post = get_object_or_404(Post, id=post_id)
    if request.user != edit_post.author:
        return redirect('posts:post_detail', post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=edit_post)
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id)
    context = {'form': form, 'is_edit': True}
    return render(request, 'posts/create_post.html', context)

yatube/users/views.py
from django.views.generic import CreateView

from django.urls import reverse_lazy

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'

yatube/templates/about/author.html
{% extends "base.html" %}
{% block title %}Об авторе проекта{% endblock %}
{% block content %}
<style type="text/css">
  <!--
  .tab { margin-left: 40px; }
  -->
  </style>
<h1>Привет, я автор этой страницы!</h1>
<p class="tab">
  <br>
    Мой аккаунт в Git-hub: <a href="url">https://github.com/Kirill-Bovin</a>
  </br>
  <br>
    Меня вдохновляет сама жизнь со всеми её примочками.
  </br>  
  <br>
    Мир программирования для меня открылся случайным образом.
  </br>  
  <br>
    Некоторые темы даются с трудом, например: декораты и валидаторы.
  </br>
</p>
{% endblock %} 

yatube/templates/about/tech.html
{% extends "base.html" %}
{% block title %}Технологии{% endblock %}
{% block content %}
<div class="row">
  <h1>Вот что я умею</h1>
  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        Python: писать функции и модули
      </li>
      <li class="list-group-item">
        Django: понял как работает связь между urls → views → models → templates
      </li>
    </ul>
  </aside>
  <article class="col-12 col-md-9">
    <p>Достаточно занятные уроки, главное чтобы был результат!</p>
  </article>
</div>
{% endblock %} 

yatube/templates/includes/block_mistakes.html
{% if form.errors %} 
    {% for field in form %}  
      {% for error in field.errors %}              
        <div class="alert alert-danger">  
          {{ error|escape }}  
        </div>  
      {% endfor %}  
    {% endfor %}  
    {% for error in form.non_field_errors %}  
              <div class="alert alert-danger">  
                {{ error|escape }}  
              </div>  
    {% endfor %}  
{% endif %} 

yatube/templates/includes/code_form.html
{% load user_filters %} 
{% for field in form %} 
  <div class="form-group row my-3" 
    {% if field.field.required %}  
      aria-required="true" 
    {% else %} 
      aria-required="false" 
    {% endif %} 
  > 
    <label for="{{ field.id_for_label }}"> 
      {{ field.label }} 
        {% if field.field.required %} 
          <span class="required text-danger">*</span> 
        {% endif %} 
    </label> 
    <div> 
    {{ field|addclass:'form-control' }} 
      {% if field.help_text %} 
        <small id="{{ field.id_for_label }}-help" class="form-text text-muted"> 
          {{ field.help_text|safe }} 
        </small> 
      {% endif %} 
    </div>
  </div>
{% endfor %}

yatube/templates/includes/footer.html
<p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>    

yatube/templates/includes/header.html
{% load static %} 
<nav class="navbar navbar-light" style="background-color: lightskyblue">
  <div class="container">
    <a class="navbar-brand" href="{% url 'posts:index' %}">
      <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
      <span style="color:red">Ya</span>tube
    </a>
    <ul class="nav nav-pills">
      {% with request.resolver_match.view_name as view_name %}
      <li class="nav-item">
        <a class="nav-link {% if view_name  == 'about:author' %}active{% endif %}" href="{% url 'about:author' %}">Об
          авторе</a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if view_name  == 'about:tech' %}active{% endif %}" href="{% url 'about:tech' %}">Технологии</a>
      </li>
    </li>
    {% if request.user.is_authenticated %}
    <li class="nav-item">
      <a class="nav-link {% if view_name  == 'posts:post_create' %}active{% endif %}"
        href="{% url 'posts:post_create' %}">Новая запись</a>
    </li>
    <li class="nav-item">
      <a class="nav-link link-light {% if view_name  == 'users:password_change_form' %}active{% endif %}"
        href="{% url 'users:password_reset_form' %}">Изменить пароль</a>
    </li>
    <li class="nav-item">
      <a class="nav-link link-light {% if view_name  == 'users:logout' %}active{% endif %}"
        href="{% url 'users:logout' %}">Выйти</a>
    </li>
    <li class="nav-item">
      <a class="nav-link link-light {% if view_name  == 'posts:profile' %}active{% endif %}"
        href="{% url 'posts:profile' user.username %}">Пользователь: {{ user.username }}</a>
    </li>
      {% else %}
    <li class="nav-item">
      <a class="nav-link link-light {% if view_name  == 'users:login' %}active{% endif %}"
        href="{% url 'users:login' %}">Войти</a>
    </li>
    <li class="nav-item">
      <a class="nav-link link-light {% if view_name  == 'users:signup' %}active{% endif %}"
        href="{% url 'users:signup' %}">Регистрация</a>
    </li>
    {% endif %}
    {% endwith %}
    </ul>
  </div>
</nav>

        
    

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}
  {% if form.instance.pk %}Редактировать пост{% else %}Новый пост{% endif %}
{% endblock %}
{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            {% if form.instance.pk %}Редактировать пост{% else %}Новый пост{% endif %}
          </div>
          <div class="card-body">
            {% include 'includes/block_mistakes.html' %}
            <form method="post"
                action="{% if form.instance.pk %} {% url "posts:post_edit" form.instance.pk %}
                        {% else %} {% url "posts:post_create" %}{% endif %}">
              {% csrf_token %}
              {% include 'includes/code_form.html' %}
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {% if form.instance.pk %}
                    Сохранить
                  {% else %}
                    Добавить
                  {% endif %}
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %} {{ group.title }} {% endblock %} 
{% block content %}
    <div class="container">
      <h1>{{ group.title }}</h1>       
      <p>{{ group.description|linebreaksbr }} </p>
      {% for post in page_obj %}
          {% include 'posts/includes/post_card.html' with flag_group=True %}
        {% if not forloop.last %}<hr>{% endif %}
      {% endfor %} 
      {% include 'posts/includes/paginator.html' %}
    </div>  
{% endblock %}

yatube/templates/posts/includes/paginator.html
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}    
  </ul>
</nav>
{% endif %}

yatube/templates/posts/includes/post_card.html
<article>
  <ul>
    <li>
      Автор: {{ post.author }}
        {% if not flag_profile %}
          <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
        {% endif %}
    </li> 
    <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
  </ul>
  <p>
    {{ post.text|linebreaks }}
  </p>
    <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>
  {% if not flag_group %}
    {% if post.group %} 
      <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
    {% endif %}
  {% endif %} 
</article>

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %} Последние обновления на сайте {% endblock %}
{% block content %}
  <div class="container">        
    <h1> Последние обновления на сайте </h1>
    {% for post in page_obj %}
      {% include 'posts/includes/post_card.html' %} 
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %} 
    {% include 'posts/includes/paginator.html' %}
  </div> 
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %}Пост {{ post_title }}{% endblock %}
{% block content %}
  <div class="container py-5">
    <div class="row">
      <aside class="col-12 col-md-3">
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            Дата публикации: {{ pub_date|date:"d E Y" }}
          </li>
          {% if post.group %}
            <li class="list-group-item">
              Группа: {{ post.group.title }}
                <a href="{% url 'posts:group_list' post.group.slug %}">
              все записи группы
            </a>
          {% else %}
            <span style='color: red'>Этой публикации нет ни в одном сообществе.</span>
          {% endif %}
          </li>
          <li class="list-group-item">
            Автор: {{ request.user.get_full_name }} {{ author }}
          </li>
          <li class="list-group-item d-flex justify-content-between align-items-center">
            Всего постов автора: <span>{{ author_posts }}</span>
          </li>
          <li class="list-group-item">
            <a href="{% url 'posts:profile' post.author %}">
              все посты пользователя
            </a>
          </li>
        </ul>
      </aside>
      <article class="col-12 col-md-9">
        <p>
          Текст поста: {{ post.text|linebreaks }}
        </p>
        {% if request.user == post.author %}
          <a class="btn btn-primary" href="{% url 'posts:post_edit' post.pk %}">
        {% endif %}    
          редактировать запись
        </a>
      </article>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}Профайл пользователя {{ post.author.get_full_name}}{% endblock %}
{% block content %}

<div class="container py-5">
  <h1>Все посты пользователя: {{ author.get_full_name }}</h1>
    <h3>Всего постов: {{ post_count }} </h3>
    {% for post in page_obj %}
      {% include 'posts/includes/post_card.html' with flag_profile=True %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
  {% include 'posts/includes/paginator.html' %}
</div>
{% endblock %}

yatube/templates/users/logged_out.html
{% extends 'base.html' %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Выход
      </div>
      <div class="card-body">
        <p>
          Вы вышли из своей учётной записи. Ждём вас снова!
        </p>
      </div> 
    </div> 
  </div> 
</div> 
{% endblock %}

yatube/templates/users/login.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
{% load user_filters %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Войти на сайт
      </div>
      <div class="card-body">
        {% include 'includes/block_mistakes.html' %}
        <form method="post"
          {% if action_url %}
            action="{% url action_url %}"
          {% endif %}
        >
        {% csrf_token %}
        {% include 'includes/code_form.html' %}
        <div class="col-md-6 offset-md-4">
          <button type="submit" class="btn btn-primary">
            Войти
          </button>
          <a href="{% url 'users:password_reset_form' %}" class="btn btn-link">
            Забыли пароль?
          </a>
        </div>
        </form>
      </div> 
    </div> 
  </div> 
</div> 
{% endblock %} 

yatube/templates/users/password_change_done.html
{% extends "base.html" %}
{% block title %}Пароль изменён успешно{% endblock %}
{% block content %}
<div class="container py-5"> 
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Пароль изменён
        </div>
        <div class="card-body"> 
          <p>Пароль изменён успешно</p>
        </div> 
      </div> 
    </div> 
  </div> 
</div>
{% endblock %} 

yatube/templates/users/password_change_form.html
{% extends "base.html" %}
{% block title %}Сброс пароля{% endblock %}
{% block content %}
<div class="container py-5"> 
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Изменить пароль
        </div>
        <div class="card-body">
          <form method="post" action="{% url 'users:password_change_form' %}">
            {% csrf_token %}
            {% include 'includes/code_form.html' %}
            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Изменить пароль
              </button>
            </div>
          </form>
        </div> 
      </div> 
    </div> 
  </div> 
</div>
{% endblock %} 

yatube/templates/users/password_reset_complete.html
{% extends "base.html" %}
{% block title %}Восстановление пароля завершено{% endblock %}
{% block content %}
<div class="container py-5"> 
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Восстановление пароля завершено
        </div>
        <div class="card-body">
          <p>Ваш пароль был сохранен. Используйте его для входа</p>
          <a href="{% url 'users:login' %}">войти</a>
        </div> 
      </div> 
    </div>
  </div> 
</div>
{% endblock %} 

yatube/templates/users/password_reset_confirm.html
{% extends "base.html" %}
{% block title %}Назначить новый пароль{% endblock %}
{% block content %}
<div class="container py-5"> 
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Введите новый пароль
        </div>
        <div class="card-body">
          <form method="post" action="{% url 'users:password_reset_confirm' %}">
            {% csrf_token %}
            {% include 'includes/code_form.html' %}
            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Назначить новый пароль
              </button>
            </div>
          </form>
        </div> 
      </div> 
    </div> 
  </div> 
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Ошибка
        </div>
        <div class="card-body">
          <p>Ссылка сброса пароля содержит ошибку или устарела.</p>
        </div> 
      </div> 
    </div> 
  </div> 
</div>
{% endblock %} 

yatube/templates/users/password_reset_done.html
{% extends "base.html" %}
{% block title %}Ваш пароль сброшен вам на почтовый ящик{% endblock %}
{% block content %}
<div class="container py-5"> 
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Отправлено письмо
        </div>
        <div class="card-body">
          <p>Проверьте свою почту, вам должно прийти письмо со ссылкой для восстановления пароля</p>
        </div> 
      </div> 
    </div>
  </div> 
</div>
{% endblock %} 

yatube/templates/users/password_reset_form.html
{% extends "base.html" %}
{% block title %}Сброс пароля{% endblock %}
{% block content %}
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Чтобы сбросить старый пароль — введите адрес электронной почты, под которым вы регистрировались
        </div>
        <div class="card-body">
          <form method="post" action="{% url 'users:password_reset_form' %}">
            {% csrf_token %}
            {% include 'includes/code_form.html' %}
            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Сбросить пароль
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/users/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">Зарегистрироваться</div>
        <div class="card-body">
        {% load user_filters %} 
          {% include 'includes/block_mistakes.html' %}
            <form method="post" action="{% url 'users:signup' %}">
            {% csrf_token %}
            {% include 'includes/code_form.html' %}
            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Зарегистрироваться
              </button>
            </div>
          </form>
        </div> 
      </div> 
    </div> 
</div> 
{% endblock %} 